workspace:
  base: /workspace
  path: ikarus-frontend

pipeline:
  setup:npm:
    image: node:12-alpine
    commands:
    - npm install

  test:spec:
    image: weboaks/node-karma-protractor-chrome:alpine-root
    commands:
    - npm run test:ci

  test:e2e:
    image: caltha/protractor
    commands:
    - npm run e2e:ci
